name: Cache GitHub README Stats

on:
  schedule:
    - cron: 0 0 * * * # Every day at 00:00
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update-assets:
    runs-on: ubuntu-latest
    steps:
    # Checkout with custom token for push to protected branch
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download stats.svg
      run: |
        mkdir -p assets
        curl 'https://readme-status-4voh.vercel.app/api?username=HaoboGu&count_private=true&show_icons=true&theme=transparent&border_color=2f80ed' -o assets/stats.svg
        curl 'https://readme-status-4voh.vercel.app/api/top-langs/?username=HaoboGu&count_private=true&show_icons=true&theme=transparent&border_color=2f80ed' -o assets/top-langs.svg

    - name: Push stats.svg
      run: |
        git config user.name "HaoboGu"
        git config user.email "haobogu@outlook.com"
        git add assets/stats.svg
        git add assets/top-langs.svg
        git commit -m "Update assets"
        git push origin
